### ISSUE TITLE
In lilv recipe get_waf_parallel_make function has been removed

### ISSUE THREAD

**Issue by Rezzonics** [auto3000/meta-pedalpi#12]
In recipe recipes-core/lilv/lilv.bb get_waf_parallel_make(d) function has been and replaced by something like oe.utils.parallel_make_argument(d, '-j%d', limit=64)

**Comment by auto3000** [comment]
Thanks, I was meeting this problem at that moment, it helps.

**Comment by auto3000** [comment]
I was figuring if "parallel" is very for a small machine. I think now we shall remove this parallelism and keep the parallelism at bitbake level... I think I will remove it

**Comment by auto3000** [comment]
I changed my mind. When I developed this recipe, I think I was happy to get the compilation faster. Let's go for oe.utils.parallel_make_argument(d, '-j%d', limit=64) and thanks again for this tip
