### ISSUE TITLE
freakclip: 1 pedal (out of the 3 from freaked recipe) is not compatible with mod-ui

### ISSUE THREAD

**Issue by auto3000** [auto3000/meta-pedalpi#26]
![image](https://user-images.githubusercontent.com/8845975/101983055-69944980-3c78-11eb-8497-bfbeffe196f4.png)

@Rezzonics I got this issue with both old mod-ui and the mod-ui on upgradedev branch

**Comment by Rezzonics** [comment]
I made Freakclip work by adding  default-preset.ttl and manifest.ttl from mod-lv2-data:
https://github.com/moddevices/mod-lv2-data/tree/master/plugins-fixed/Freaktail.lv2

**Comment by auto3000** [comment]
Good catch.
